# Generated by Django 6.0.5 on 2026-05-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tile',
            new_name='title',
        ),
    ]
